### ISSUE TITLE
Assets are uploaded as 34 byte

### ISSUE THREAD

**Issue by mldev-py** [marvinpinto/actions#10]
![Screen Shot 2019-11-12 at 4 44 15 AM](https://user-images.githubusercontent.com/53791498/68640166-2f052e00-0507-11ea-849b-63f338b831e2.png)

Hello, @marvinpinto 
Why are assets uploaded as 34 bytes since v0.2.1?

**Comment by marvinpinto** [comment]
Oops! Something has definitely gone wrong there. Thanks for pointing it out!

**Comment by lexelby** [comment]
The file contents are:

```
== raw file buffer info removed ==
```

Any way I can help debug?

**Comment by marvinpinto** [comment]
Hey @lexelby! I haven't looked at it this yet but if you're up for having a look yourself and possibly PRing a fix, I would be much obliged!

If not I'll get around to it in the next few weeks or so.

**Comment by lexelby** [comment]
I'll see what I can do. :)  I'm not great at node and I don't know much about octokit, but this seems like it should be a relatively simple problem...

**Comment by uint-jamf** [comment]
Lines 10501-10517:
```
exports.octokitLogger = (...args) => {
    return args
        .map(arg => {
        if (typeof arg === 'string') {
            return arg;
        }
        // Do not log file buffers
        if (arg.file) {
            arg.file = '== raw file buffer info removed ==';
        }
        if (arg.data) {
            arg.data = '== raw file buffer info removed ==';
        }
        return JSON.stringify(arg);
    })
        .reduce((acc, val) => `${acc} ${val}`, '');
};
```

I'm guessing this function (closure?) has side effects that it shouldn't. If the actual data is passed by reference and we're modifying that, it would make a lot of sense.

The quickest thing would be to create some kind of deep copy of each arg and remove the raw binary data from it then, but that sounds horrible for large files. Otherwise a better way would be to write a custom parser for file buffers that stringifies metadata while ignoring the blob? Or just extract the filename and give up on logging the rest of it.

I don't think I'll be touching this - I'm not a node person. Just throwing my thoughts in here.

**Comment by lexelby** [comment]
Thanks!  Now in really wondering why my googling didn't find that...

The solution is probably as simple as not logging the file handle.

**Comment by marvinpinto** [comment]
This should be fixed by @matteocodogno in #11. Feel free to reopen if you notice anything amiss. Thanks all!

**Comment by lexelby** [comment]
Yay!! Thanks all!  Will you make a new release with the fix?  Oh, I bet releases are automatic, huh? ;)

**Comment by marvinpinto** [comment]
@lexelby Yeah, there should have already been a release tagged `latest` as soon as this was merged to master. Again, if this isn't the case, open up an issue and I can have a look :+1:

**Comment by niess** [comment]
Hello @marvinpinto. This is just to let you know that currently the [market place](https://github.com/marketplace/actions/automatic-releases) points to v0.2.2 of `automatic-releases` as the latest release which has the 34 bytes bug.

The curent latest release works fine :) Thank you for this GitHub action. It is very convenient.

**Comment by marvinpinto** [comment]
@niess  I updated the marketplace release versions to point to the latest, thanks for the reminder! I am hoping they release an API to automate this at some point.

**Comment by niess** [comment]
@marvinpinto : very good. Generally speaking, it is indeed annoying that the latest version of an action is not automatically detected. But at least now that I know about this issue I'll take care next time :)
