### ISSUE TITLE
Question about GITHUB_SUPER_TOKEN

### ISSUE THREAD

**Issue by techno-sam** [marvinpinto/actions#123]
In .github/workflows/pre-release.yml, Line 56, what is secrets.GITHUB_SUPER_TOKEN. When I try to use this in my fork, it doesn't work.

**Comment by marvinpinto** [comment]
I use the `GITHUB_SUPER_TOKEN` to mirror this repository to the individual action repos, which in turn are published to the marketplace. You should try and avoid running that build from your fork 👍🏾
