### ISSUE TITLE
action-automatic-releases@latest doesn't clean the commit list when executed inside a matrix job

### ISSUE THREAD

**Issue by israpps** [marvinpinto/actions#151]
This is my workflow
https://github.com/israpps/FreeMcBoot-Installer/blob/c06d4fc4fc54e4b6274c3eb1722f75151f456aeb/.github/workflows/compile-core.yml

Since I've implemented the matrix into my job the commit list isn't erasing the old commits.

**Comment by marvinpinto** [comment]
I'm afraid I cannot help troubleshoot what exactly is happening here. If you can sort out exactly why this is happening with something small and reproducible I'll gladly look into it.

**Comment by israpps** [comment]
Your action doesn't clean the commit list on the release tab when executed.
That's why I had to place your action in another job (that doesn't have matrix).
