### ISSUE TITLE
action-automatic-releases@v1.2.0 not detecting the latest commit from git history

### ISSUE THREAD

**Issue by rjga94** [marvinpinto/actions#159]
Hi,

I have a workflow where the first step is to update a project file (to update the version in the project) and a second step which does the github release.
The results i excepted is to have this new automatic commit tagged with a release from github, but that is not the case, what happens is that the previous commit to the automatic one is the one that gets tagged.

Here's my workflow: https://gist.github.com/rjga94/685bc79c2ca99c8863da5cc62ee887cf

**Comment by rjga94** [comment]
After some more research it seems that any change to Git within the same workflow won't be picked up by `action-automatic-releases@v1.2.0`.

**Comment by marvinpinto** [comment]
The automatic releases action was not designed to work with `workflow_dispatch` events, a lot would need to change for this to work.
