### ISSUE TITLE
action-automatic-releases always raise a "doesn't match any files" error

### ISSUE THREAD

**Issue by Danixu** [marvinpinto/actions#236]
Hello,

Some time ago I have started to use this action to automatically create releases for my program. On my first tests was working fine, but now without changing anything beyond the makefile (the releases folder and the zip files are the same).

I have the following steps on my github build script:

```
     - name: Generate release
        run: |
          cd release
          zip -r ecm_${{ env.RELEASE_VERSION }}_linux.zip linux/*
          zip -r ecm_${{ env.RELEASE_VERSION }}_win64.zip win64/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            'release/*.zip'
```

I am fully sure that the zip files are created because I have added some ls commands and I am able to see it, and also I can see in the log how files are compressed, but the automatic release always gives an error `'release/*.zip' doesn't match any files`.

I have even tried the full path with the full filename instead to use the wildcard, and I got the same error.

What is the correct way to use it?

Thanks!

**Comment by ricardolpd** [comment]
I am having a similiar issue, if I generate any files/folder with a previous step, those are not captured by this action, however if i use file belonging to the repo, the plugin works as expected. Is there any reason why this plugin wont see generated files?

**Comment by ricardolpd** [comment]
@Danixu i managed to get it working by adding `./` in front of the file i want to export in your case it should be `./release/*.zip`

**Comment by Danixu** [comment]
Nice!, but mine still failing...

<a href="https://ibb.co/B3Djdf7"><img src="https://i.ibb.co/LRw6b0q/error.png" alt="error" border="0"></a>

I'll try to create the zip files in root folder to see. Maybe is the folder name or something similar.

Best regards.

**Comment by Danixu** [comment]
Finally I have found the problem... were just the quotation marks, I have changed `"release/*.zip"` to just `release/*.zip` and now is working fine.
