### ISSUE TITLE
Creating release with this does not trigger my other workflow which is dependent on release published event.

### ISSUE THREAD

**Issue by iamriajul** [marvinpinto/actions#24]
I have two workflow,

One is for building and deploying the application, and it is triggered by Github release feature, I check if the release is pre-release or not, if pre-release then I build beta version of my app and deploy otherwise stable version.

Another is with this action which is triggered by Tag Push, I create tag from my IDE using name like v5.5.1-beta or v5.5.2, in this workflow, I decide whether to create pre-release or stable release.

That's how workflows are installed.
but the Tag push workflow with this action creates a release in Github but my Build and Deploy workflow doesn't run on the create release event triggered by this action.

Thanks.

Action: marvinpinto/action-automatic-releases

**Comment by marvinpinto** [comment]
Hey there!

I believe workflows [cannot trigger other workflows](https://help.github.com/en/actions/reference/events-that-trigger-workflows) when using `GITHUB_TOKEN` (which the automatic-releases action uses).

You might be able to work around that with a manual trigger (using a personal access token), but that's beyond the scope of this.
