### ISSUE TITLE
Only include commits with specific PR label

### ISSUE THREAD

**Issue by jneeven** [marvinpinto/actions#256]
Hi, first of all thanks for this action! It's very nice to be able to see the latest version of a package right from the repo homepage without any manual work. I just have one question regarding the automatically generated release notes: would it be possible to only include commits / PRs with a specific label? Not all the commits I make will be relevant to the package itself.

Thanks!

**Comment by marvinpinto** [comment]
Hey there :wave:

I don't think I will add that functionality to the automatic releaser action. As a manual workaround, you could edit the release notes post-release and remove the commits you don't need.
