### ISSUE TITLE
Possibility of changing author of release

### ISSUE THREAD

**Issue by srevinsaju** [marvinpinto/actions#26]
I am not sure if this is possible; But for automatic-release; it would be very nice if I could fake my account as the author of the PR instead of `github-actions`. I am not sure if its already implemented (did not find any information as such in the documentation)

**Comment by marvinpinto** [comment]
Hello!

I don't believe it's possible to change the author name unfortunately. If they do allow this at some point I'd love to make it configurable :+1:
