### ISSUE TITLE
  Error: File size (2919235584) is greater than possible Buffer: 2147483647 bytes 44

### ISSUE THREAD

**Issue by davibe** [marvinpinto/actions#271]
self-explanatory :)

**Comment by marvinpinto** [comment]
I am not sure what you would like here?

**Comment by davibe** [comment]
It should be possible to upload files that are bigger than 2147483647

**Comment by marvinpinto** [comment]
Hey! Is this a limitation on the GitHub API, in the node library, or somewhere in Node? If you can track it down and are willing to submit a reasonably-sized pull request I would consider including it. I am probably not going to track this issue down.

**Comment by davibe** [comment]
That is a Buffer (javascript/node). I do not think it's a github limitation. Probably you are trying to load too much stuff in a single Buffer instead of streaming incrementally. I did not investigate too much in the code of this plugin

**Comment by davibe** [comment]
I had a quick look but it's unclear to me where this comes from:
client.repos.uploadReleaseAsset
