### ISSUE TITLE
add files from artifacts as assets

### ISSUE THREAD

**Issue by tobiasfaust** [marvinpinto/actions#28]
i case of a build strategy matrix multiple files are relevant as assets.
It would be helpful if you are able to define filenames with a pattern from the artifacts who will be upload as assets.

example:
artifactfiles: |
  *.bin

**Comment by marvinpinto** [comment]
Hi there,

Multi-line glob patterns _should_ already work - have you come across a situation it doesn't?

There's an example of a glob pattern in the [README](https://github.com/marvinpinto/actions/blob/master/packages/automatic-releases/README.md).

**Comment by tobiasfaust** [comment]
Hi Marvin,
i have been looking for possibility to add artifacts from a previous run matrix. In your examples you add only present files from Unix folders 

Example:
Jobs:
  - build:
    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:uno
          - esp8266:esp8266:d1_mini
          - esp32:esp32:nodemcuv2
      steps:
        - compile code....
        - uses: actions/upload-artifact@v2

  - create_Release:
    ...... -> at this point all 3 binaries (avr, esp8266, esp32) files from job "build" are lost at unix harddisk, only available via artifacts

**Comment by marvinpinto** [comment]
Hello! I think GitHub actions runs each job in a separate container, which is why you're probably not seeing the artifacts from the previous matrix. I vaguely recall reading this in their [help forums](https://github.community/c/github-actions/41).

Could you verify if accessing artifacts across jobs is possible?

**Comment by l3laze** [comment]
It seems to need the upload_url from creating the release to be output so it could be saved and used similar to [this script](https://github.com/actions/create-release/issues/14#issuecomment-555379810).

**Comment by marvinpinto** [comment]
Adding the `upload_url` as an output seems like a reasonable (and low maintenance) thing to add if anyone is interested :+1:

We'll track that separately though.
