### ISSUE TITLE
Action automatic releases fails generating changelog

### ISSUE THREAD

**Issue by SweetSofiMC** [marvinpinto/actions#281]
When running [GitHub Automatic Releases](https://github.com/marvinpinto/action-automatic-releases), it fails when **Generating Changelog** with error: _Resource not accessible by integration_

![image](https://user-images.githubusercontent.com/7455707/131881166-ca14b175-ff0d-4b8e-aeb8-9364ff841e78.png)

I have permissions write-all in the action for the GitHub token, also, if relevant, it's a private repository

**Comment by marvinpinto** [comment]
I briefly googled that error and it looks like something permissions related. You might need to experiment around and see what that's happening.

**Comment by 1038642892** [comment]
I came across a similar error, potentially we were both using a fine grained token without the necessary permissions.

I couldn't find a list of required permissions on the repo README but this is what I'm using with success:

**Repository permissions**

1. Read access to metadata
2. Read and Write access to code and pull requests
