### ISSUE TITLE
Title not used when set 

### ISSUE THREAD

**Issue by mitm001** [marvinpinto/actions#31]
Custom title is not set when using the title key  and not using the automatic_release_tag.

https://github.com/mitm001/jme-ui/blob/0755c4c138613f98c49051a918ecb2f889e35429/.github/workflows/release.yml#L40-L56

https://github.com/mitm001/jme-ui/releases

Am I not using this correctly?

**Comment by marvinpinto** [comment]
It looks like you already figured this out :+1:

(reopen if there's something else)
