### ISSUE TITLE
Syntax error in action.yml

### ISSUE THREAD

**Issue by tcamargo** [marvinpinto/actions#36]
There is a small typo in packages/automatic-releases/action.yml.

##[error]marvinpinto/action-automatic-releases/latest/action.yml (Line: 27, Col: 5): Unexpected value 'decription'
See: https://github.com/libretro/mame/runs/942138167?check_suite_focus=true

Strange is that I got no error in my repo: https://github.com/tcamargo/mame/runs/941527950?check_suite_focus=true

Anyway, should be an easy fix.

**Comment by tcamargo** [comment]
Interesting. 
My repo uses an old runner version: Current runner version: '2.267.1'
Libretro repo uses a new one: Current runner version: '2.272.0'

**Comment by maximousblk** [comment]
patch: #37

**Comment by xurion** [comment]
Thanks for the fix!

What is the versioning strategy for the action? I had to point the action to use @master, which will eventually fail if/when compatibility breaks are implemented in the future.
