### ISSUE TITLE
Error due to github changes

### ISSUE THREAD

**Issue by lamest** [marvinpinto/actions#39]
I started to get this error today

Download action repository 'marvinpinto/action-automatic-releases@v1.0.0'
##[error]marvinpinto\action-automatic-releases\v1.0.0\action.yml (Line: 27, Col: 5): Unexpected value 'decription'
##[error]marvinpinto\action-automatic-releases\v1.0.0\action.yml (Line: 27, Col: 5): Unexpected value 'decription'
##[error]Fail to load marvinpinto\action-automatic-releases\v1.0.0\action.yml

**Comment by marvinpinto** [comment]
Hey! I'm pretty sure this is related to https://github.com/marvinpinto/actions/pull/38. As I mentioned there, you can use `@latest` until I cut a versioned release :+1:
