### ISSUE TITLE
Set-env is being deprecated

### ISSUE THREAD

**Issue by vintagepc** [marvinpinto/actions#48]
Just a heads up that github is deprecating set-env and this action may break as a result:

![image](https://user-images.githubusercontent.com/53943260/95668701-7ea00f80-0b45-11eb-8388-08c88207ba51.png)

**Comment by sormuras** [comment]
https://github.com/marvinpinto/actions/blob/65b0369698099875792ef0515103f3e78c3babd3/packages/automatic-releases/src/main.ts#L317-L322

Could be resolved by "simply" updating `actions/core` as suggested in #47

**Comment by marvinpinto** [comment]
Hey there, yes, part of getting this done is merging #47 - but the other bigger part is updating all the tests to work with the `set-env` replacement. I'll get to this when I have some time :+1:

**Comment by marvinpinto** [comment]
GitHub has updated the deprecation date for the `set-env` (and related) commands to Nov 16, 2020.

Ref: https://github.com/actions/runner/pull/796/files

**Comment by folex** [comment]
Now it gives an error in the build :(

```Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

**Comment by sormuras** [comment]
Despite the error message, a) uploading artifacts still works and b) the step is not **(yet)** marked as failed:

https://github.com/sormuras/simplicissimus/runs/1390061885?check_suite_focus=true#step:7:44

**Comment by Jarek606** [comment]
What about this? Somebody change implementation? Because it raise error on builds :/

**Comment by marvinpinto** [comment]
I updated all the GitHub actions in this repo to use the set-env replacement - see https://github.com/marvinpinto/actions/pull/52

This should get auto deployed and available soon under the `latest` tag. If there are no issues in the next week or so, I'll cut an actual release :+1:

**Comment by sormuras** [comment]
Works for me: https://github.com/sormuras/sawdust/runs/1404422492?check_suite_focus=true#step:7:1

Thanks for the update, Marvin!
