### ISSUE TITLE
Determining release tags step fails

### ISSUE THREAD

**Issue by rdab** [marvinpinto/actions#51]
Hello (and thanks for your time in this action):

I have found that release fails when tag doesn't conform with SemVer format `x.y.z`. I'm using Calver format like `YYYY.MM[.PATCH]` where Patch is optional. Whenever the tag is like `YYYY.MM` it fails with the following error:

```
Run marvinpinto/action-automatic-releases@v1.1.0
Initializing the Automatic Releases action
Determining release tags
  Error: The parameter "automatic_release_tag" was not set and the current tag "v2020.11" does not appear to conform to semantic versioning.
```

Here is my current step config:
```
...
      - name: Upload Release Assets
        uses: "marvinpinto/action-automatic-releases@v1.1.0"
        with:
          title: Release ${{ github.event.release.tag_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.release.tag_name }}
          prerelease: false
          files: |
            ./build_path/*
...

Thanks

**Comment by marvinpinto** [comment]
Hey there! This action uses a semver parsing library underneath - which basically does all the heavy lifting. I am not sure how I would go about adding Calver versioning capability as well. Unfortunately this is probably out of scope.

Thanks for taking the time to write up a detailed bug report, really appreciate it :+1:
