### ISSUE TITLE
Generate changelog even when specifying a semver compatible automatic_release_tag

### ISSUE THREAD

**Issue by rnoda** [marvinpinto/actions#54]
First, I'd like to thank you for the great work and functionality provided by this action.

I'd like to use this action within a workflow where I first generate the semver tag using other means, then use this action to create the release and upload the assets.

With that in mind, I was wondering if it would be possible to pass the newly generated tag name in the **automatic_release_tag** arg and still have your action generate the changelog with all commits since the previous semver compatible tag.

Currently, if the **automatic_release_tag** is provided, the action does not search for the previous semver compatible tag, therefore no commits are found and no changelog is generated.

Thanks!

**Comment by ellavas** [comment]
Any news on this topic ? I have the same issue, the changelog is missing when automatic_release_tag is used.

**Comment by marvinpinto** [comment]
I think this should get covered by https://github.com/marvinpinto/actions/issues/68 and so I'll close this issue. Do re-open if you disagree :+1:
