### ISSUE TITLE
Move to node 16

### ISSUE THREAD

**Issue by ldeluigi** [marvinpinto/actions#543]
Currently some actions are still using node 12 instead of node 16, which raises warnings and errors

**Comment by maggie0002** [comment]
This is untested, can you see if this fixes the issue? https://github.com/marvinpinto/actions/pull/546

**Comment by SimonLammer** [comment]
This is the concrete warning annotation shown in the workflow summary (when using `@latest`):

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: marvinpinto/action-automatic-releases

**Comment by glensc** [comment]
There are no errors. just warnings

**Comment by james-crocker** [comment]
Correct; no errors at the moment. But per link documentation GitHub support for Node12 is _deprecated_ and may easily become an 'error' condition sometime in the Summer of 2023.

**Comment by Vadorequest** [comment]
I am encountering a similar issue, my GH action relies on this action, I'm getting the warning regarding node16 as well.

It would be best to address this ASAP. Here are the things I had to do for my actions:
- https://github.com/UnlyEd/github-action-await-vercel/pull/77/files
- https://github.com/UnlyEd/github-action-await-vercel/commit/648f55305a5f056b9bf7c862fe371ce2f00e3e4f

**Comment by dimaqq** [comment]
@marvinpinto 🙏🏻

**Comment by bdlake** [comment]
+1

**Comment by whanata** [comment]
+1

**Comment by jensenbox** [comment]
Any movement on this?

```text
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: marvinpinto/action-inject-ssm-secrets@latest. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

It is only annoying and definitely not life-threatening.

**Comment by SimonDarksideJ** [comment]
> It is only annoying and definitely not life-threatening.

Actually, GitHub are deprecating actions using older Node versions (along with set-output) and they will cease to function after that.

**Comment by HiranChaudhuri** [comment]
Whatever may be going on in the background: As long as these changes are not released they are not usable by other workflows.
Hence I am wondering why all these issues get closed.

**Comment by sbe-arg** [comment]
We are rebumping this project a bit mainly the releases part stay tunned
