### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by ldeluigi** [marvinpinto/actions#544]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

You should move to the new syntax: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Also I suggest to check out https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary which seems a cool new feature

**Comment by maggie0002** [comment]
This is untested, can you see if this fixes the issue? https://github.com/marvinpinto/actions/pull/546

**Comment by SimonLammer** [comment]
This is the concrete warning annotation shown in the workflow summary (when using `@latest`):

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by wiverson** [comment]
Not to be an alarmist or anything, but the GitHub post on this topic states:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

That's not very far out - any news or updates?

**Comment by AngellusMortis** [comment]
It is now May and June is coming up fast. Has anyone forked and made a drop in replacement yet?

**Comment by gbakeman** [comment]
As far as automatic releases are concerned, I've been using https://github.com/softprops/action-gh-release and pretty happy with that. I don't think it has automatic changelog generation though.
