### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by eyal0** [marvinpinto/actions#61]
I got an error from the release action.

```
Generating release tag
  Attempting to create or update release tag "latest"
  Could not create new tag "refs/tags/latest" (Resource not accessible by integration) therefore updating existing tag "tags/latest"
  Error: Resource not accessible by integration
  (node:2449) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:357542
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:2449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:2449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eyal0** [comment]
Ah, looks like it's because I was running it on pull request and not on push to branch.  The pull requests run with read-only permissions because they are made by other users.  But a push is made by a user with write access to the repo, so those have write permission to create a release.

I'm testing it now.  I'll re-open this issue if I still have a problem.

**Comment by pojntfx** [comment]
Ran into this because it looks like the default tokens only have read permission; you can enable read & write under Settings →Actions:

![Screenshot of the workflow permissions settings](https://user-images.githubusercontent.com/28832235/215303410-a67131da-9364-450a-8a74-4bd2a2b5df26.png)

**Comment by lrnv** [comment]
Thanks @pojntfx for finding the reason :)

**Comment by xackery** [comment]
Also if you copy paste another action and inline this, be sure to check for:
```yaml
name: Platform Tests & Build
on: [push]
permissions:
  contents: read
```

the `permission` flag will override the one pojntfx noted.
