### ISSUE TITLE
Automatic releases raises warnings - Node.js 12 actions are deprecated. 'set-output' is deprecated.

### ISSUE THREAD

**Issue by SimonDarksideJ** [marvinpinto/actions#637]
The following warnings are generating using the Automatic releases action:

* Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: marvinpinto/action-automatic-releases@latest. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mgree** [comment]
Seems like a duplicate of #543 and #544.

**Comment by SimonDarksideJ** [comment]
Confirmed duplicate of existing tasks

**Comment by Tsuk1ko** [comment]
But it seems that there is no new version publish to https://github.com/marvinpinto/action-automatic-releases

Its code is still two years ago.
