### ISSUE TITLE
automatic release action renames my file.

### ISSUE THREAD

**Issue by israpps** [marvinpinto/actions#66]
i'm trying to release a zip file named this way:
`FunTuna[$SHA].zip `
where $SHA is a variable that holds the first seven characters of the commit-SHA

taking 41e4ebe as an SHA example....

I expected this filename:

`FunTuna[41e4ebe].zip`

I'm getting this:

`FunTuna.41e4ebe.zip`

how can i get the filename that i expect?

**Comment by marvinpinto** [comment]
I don't really have any context on what is happening here. Without more information on how I can reproduce this I'm afraid I cannot help.

**Comment by israpps** [comment]
> I don't really have any context on what is happening here. Without more information on how I can reproduce this I'm afraid I cannot help.

you want context?
there you have: https://github.com/israpps/wLaunchELF_ISR/tree/master
