### ISSUE TITLE
action-automatic-releases export urls?

### ISSUE THREAD

**Issue by cathaysia** [marvinpinto/actions#71]
Could let action-automatic-releases export releases's urls? I just want action send me a email contains these urls. So I don't need sign in github to get this urls.

**Comment by marvinpinto** [comment]
Hello! I'm not entirely sure what you mean by releases urls? I suspect this might be out of scope for the automatic releases action though.

**Comment by cathaysia** [comment]
> 
> 
> Hello! I'm not entirely sure what you mean by releases urls? I suspect this might be out of scope for the automatic releases action though.

When my releases were published, it give a email surely, but when my assets are lot, it only send me source.zip and source.tar.gz 's url. Others are ignore.

Give a try of https://github.com/cathaysia/youtube-download-and-release !
