### ISSUE TITLE
Error: Unable to process command ::set-env with action-automatic-releases@v1.1.0

### ISSUE THREAD

**Issue by devhawk** [marvinpinto/actions#73]
I haven't had any issue using this action previously, though I recently switched from @latest to @1.1 of the action. This morning, I made unrelated changes to the workflow and it gave me the error below.

https://github.com/ngdenterprise/neo-blockchaintoolkit-library/runs/2168092633?check_suite_focus=true

```
Error: Unable to process command '::set-env name=AUTOMATIC_RELEASES_TAG,::1.0.30-preview' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by marvinpinto** [comment]
Hey! this was reported and fixed a while back - tag 1.1.0 is pretty old. I cut a new release today anyway so you should be able to use that :+1:
